version: "3.8"

services:
  mysql8:
    image: mysql:8
    container_name: mysql-8
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
volumes:
  mysql-data: